/**
 * 
 */
package com.newpage.dynamo.entity;

import java.util.Date;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

/**
 * @author abhinab
 *
 */
@Data
@DynamoDBTable(tableName = "App_Health")
public class AppHealth {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute(attributeName = "App")
  private String app;

  @DynamoDBAttribute(attributeName = "TimeStamp")
  private Date timeStamp;

  @DynamoDBAttribute(attributeName = "SubjectID")
  private long subjectId;

  @DynamoDBAttribute(attributeName = "SessionID")
  private long sessionId;

  @DynamoDBAttribute(attributeName = "TaskVersion")
  private long taskVersion;

  @DynamoDBAttribute(attributeName = "TaskBlock")
  private String taskBlock;

  @DynamoDBAttribute(attributeName = "TrailId")
  private long trailId;

  @DynamoDBAttribute(attributeName = "Error_Reason")
  private String errrorReason;

  @DynamoDBAttribute(attributeName = "Json")
  private byte[] json;

  @DynamoDBAttribute(attributeName = "Status")
  private boolean status;

}
